version: '3'
services:
  backend:
    build:
      context: .
      dockerfile: ./docker/backend/Dockerfile 
    container_name: platform_backend
    ports:
      - "8080:8080"
    networks:
      - common_network
  
  frontend:
    build:
      context: .
      dockerfile: ./docker/frontend/Dockerfile 
    container_name: platform_frontend 
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
        - common_network

networks:
  common_network:
